# Generated by Django 4.0.2 on 2022-03-23 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('zip', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=180)),
                ('contact', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=10)),
                ('zip', models.CharField(max_length=6, null=True)),
                ('city', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=180, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('zip', models.CharField(max_length=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couriers_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=80)),
                ('r_contact', models.CharField(max_length=10)),
                ('r_address', models.CharField(max_length=180)),
                ('r_city', models.CharField(max_length=100)),
                ('r_zip', models.CharField(max_length=6)),
                ('track_no', models.IntegerField(max_length=6)),
                ('pickup_datetime', models.DateTimeField(auto_now_add=True)),
                ('drop_date', models.DateField()),
                ('status', models.CharField(max_length=120, null=True)),
                ('cost', models.IntegerField()),
                ('pack_details', models.CharField(max_length=200, null=True)),
                ('pick_up_depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couriers_app.depot')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couriers_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TrackStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couriers_app.packagedetail')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=180)),
                ('city', models.CharField(max_length=120)),
                ('zip', models.CharField(max_length=6)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couriers_app.depot')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
