# Generated by Django 4.0.2 on 2022-03-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetail',
            name='track_no',
            field=models.IntegerField(),
        ),
    ]
