# Generated by Django 4.0.2 on 2022-03-25 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('couriers_app', '0002_alter_packagedetail_track_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
