# Generated by Django 4.0.2 on 2022-03-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers_app', '0003_company_company_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='email',
            new_name='company_email',
        ),
    ]
