# Generated by Django 4.0.2 on 2022-03-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers_app', '0004_rename_email_company_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contact',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
