# Generated by Django 4.0.2 on 2022-03-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers_app', '0005_employee_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-03-23'),
            preserve_default=False,
        ),
    ]
