# Generated by Django 4.0.2 on 2022-03-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers_app', '0008_alter_packagedetail_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetail',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
