# Generated by Django 4.0.2 on 2022-03-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers_app', '0009_alter_packagedetail_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackstatus',
            name='package',
        ),
        migrations.AddField(
            model_name='trackstatus',
            name='track_no',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
